### ISSUE TITLE
Block break errors

### ISSUE THREAD

**Issue by chrismin13** [chrismin13/VanillaAdditions#4]
Reported by ArZor

https://discordapp.com/channels/346010884809818112/346011652015259649/486940498943148032

https://pastebin.com/DWBNGfhL
https://pastebin.com/RrFquX3C

**Comment by chrismin13** [comment]
More errors! :D

`[13:11:44 ERROR]: Could not pass event CustomItemBlockBreakEvent to VanillaAdditions v1.3.3
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at com.chrismin13.additionsapi.listeners.vanilla.BlockBreak.onBlockBreak(BlockBreak.java:23) ~[?:?]
at sun.reflect.GeneratedMethodAccessor231.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:123) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1165) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lorg.bukkit.block.BlockFace;
at com.chrismin13.vanillaadditions.abilities.ChiselAbilities.convertToChiseled(ChiselAbilities.java:40) ~[?:?]
at com.chrismin13.vanillaadditions.listeners.ChiselListener.onBlockBreak(ChiselListener.java:42) ~[?:?]
at sun.reflect.GeneratedMethodAccessor234.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1-R0.1.jar:git-Spigot-500ff5d-1cead62]
... 25 more`

**Comment by chrismin13** [comment]
MOAR https://pastebin.com/raw/KD08i00f
